version: '3'

services:
  shieldtag_auth_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      PORT: ${APP_PORT}
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    container_name: redis-shieldtag
    restart: unless-stopped
    ports:
      - "6379:6379"
