version: '3'

services:
  shieldtag_auth_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}"
    environment:
      PORT: ${APP_PORT}
    volumes:
      - .:/app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
